### ISSUE TITLE
is there a method to remove all unused import class?

### ISSUE THREAD

**Issue by nshen** [Sammons/ts-import-assistance#12]
is there a method to remove all unused import class?
is that possible? tks

**Comment by Sammons** [comment]
Not yet! This project doesn't use a formal javascript / typescript parser, so I'm unsure how technically correct the solution will be, but I've been thinking about it, and there should be a way.

Essentially the gist of the method will be to split the contents of the whole document into pieces, invert that into a lookup table - then parse the existing imports and see if they exist in the document outside of the import statement.

This method leverages the fact that every imported symbol is used explicitly if it is used.

for example
`import * as fs from 'fs'` is used with `fs.methodName`, and `import {a,b,c} from 'something'` is used when `a`,`b`, or `c` appear in the document. 

The known issue with this method is that you could always name a variable `a` or `b` or `c` and then the extension would be unable to tell the difference between the import usage, and the variable usage. Doing this would require properly parsing the text and programmatically understanding the scoping of variables.

**Comment by Sammons** [comment]
@nshen I am stopping development on this project in leu of https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero which has much more focused development behind it. I will continue to monitor this repo though.
