### ISSUE TITLE
Make quotation character configurable

### ISSUE THREAD

**Issue by ngocvantran** [Sammons/ts-import-assistance#13]
Please make the quotation character configurable as I believe there are quite some of us who uses `"` instead of `'`.

**Comment by Sammons** [comment]
@7Pass would it be alright if we detected this from the current file? Just checking what you already seem to be using?

**Comment by ngocvantran** [comment]
Yes, that will be even better.

**Comment by Sammons** [comment]
@7Pass I'll get to it as soon as I can.

**Comment by Sammons** [comment]
@7Pass should be in 0.0.9, let me know how that works for you :)

**Comment by ngocvantran** [comment]
Works great. Thank you.
