### ISSUE TITLE
Can't find custom typescript annotations

### ISSUE THREAD

**Issue by mertdeg** [Sammons/ts-import-assistance#17]
This tool can find normal classes but it can't find a custom annotation (declared as a function).

**Comment by Sammons** [comment]
@mertdeg I am stopping development on this project in leu of https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero which has much more focused development behind it. I will continue to monitor this repo though. I really just didn't have the time to keep this maintained, and it was just a temporary solution I created for myself until better solutions evolved in the marketplace - I think those are here now.
