### ISSUE TITLE
Imports default exported symbols as named symbols

### ISSUE THREAD

**Issue by Chudesnov** [Sammons/ts-import-assistance#18]
Steps to reproduce: 
1. Clone https://github.com/Chudesnov/tsia-bug and open the project folder in VSCode
2. Open index.js
3. Use `Resolve and import symbol`

Expected:
`import Klass from './module'`

Actual:
`import {Klass} from './module' // does not exist`

**Comment by Sammons** [comment]
@Chudesnov Is this a use case newer libraries don't handle? I originally built this before better tools existed - like https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero - which is what I use now. You can still keybind ctrl + i to import symbol under cursor too. 

If newer tools aren't handling it I think its doable here. The big difference between this tool and others is that I just hack my way through text parsing and symbol lookup to get the job done - I don't actually use a language server or anything.

**Comment by Chudesnov** [comment]
I tried the same project structure with TypeScript Hero, and its auto-resolve mechanism seems to work as expected with TS (it even displays a prompt to provide a local name for the default export), but with jsconfig.json no .js files are even being added to the index.

Thanks for pointing out the differences! Maybe I'll try to implement the default export case in a fork.
