### ISSUE TITLE
Imports incorrectly are added above /// <reference ... /> lines instead of below

### ISSUE THREAD

**Issue by bytenik** [Sammons/ts-import-assistance#9]

**Comment by Sammons** [comment]
@bytenik should be fixed in 0.0.6, this one is a bit tricky since I think triple slash refs can have block comments before them.

Please confirm when you get a chance.

Thanks!

**Comment by bytenik** [comment]
Unable to test due to the new bug introduced re: issue #10. Once that's resolved I'll check this too.

**Comment by bytenik** [comment]
Nevermind, found a way to test this. Its fixed.
